config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :teams
  resources :matches
  resources :pages
  root 'pages#index'
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team, optional: true
  validates :name, :length => { :in => 3..20 }, :format => { :with => /\A[^0-9`!@#\$%\^&*+_= ]+\z/, :message => " contains inappropriate character(s)" }
  validates :surname, :length => { :in => 3..20 }, :format => { :with => /\A[^0-9`!@#\$%\^&*+_= ]+\z/, :message => " contains inappropriate character(s)" }
  validates :nickname, :length => { :in => 3..20 }, :format => { :with => /\A[a-zA-Z0-9_]+\z/, :message => " contains inappropriate character(s)" }
  validates :salary, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than_or_equal_to: 0 }
  validate :date_of_birth_in_future?
  validate :nickname_unique?
  validate :at_least_twelve?

  private

  def nickname_unique?
    if Player.where.not(id: self.id).exists?(:nickname=>self.nickname)
      errors.add("Player with that nickname", "already exists")
    end
  end

  def date_of_birth_in_future?
   if self.date_of_birth > Date.today
     errors.add("Date of birth", "cannot be in the future")
   end
  end

  def age_in_completed_years (bd, d)
    a = d.year - bd.year
    a = a - 1 if ( bd.month >  d.month or
        (bd.month >= d.month and bd.day > d.day))
    a
  end

  def at_least_twelve?
   if age_in_completed_years(self.date_of_birth, Date.today) < 12
     errors.add("Player must be at least", "12 years old")
   end
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  def index
    if params[:search]
      @players = Player.search(params[:search]).order("created_at DESC")
    else
      @players = Player.order("#{sort_column} #{sort_direction}")
    end
  end

  def show
  end

  def new
    @player = Player.new
    @teams = Team.all.order(:name)
  end

  def edit
    @teams = Team.all.order(:name)
  end

  def create
    @player = Player.new(player_params)
    @teams = Team.all.order(:name)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @teams = Team.all.order(:name)
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @player.destroy
    redirect_to players_path, notice: 'Player was successfully deleted.'
  end

  private

    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :surname, :nickname, :salary, :date_of_birth, :team_id)
    end

    def sortable_columns
      ["name", "surname", "nickname", "date_of_birth"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/players_helper.rb
module PlayersHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    arrowfinal = arrow(column)
    link_to "#{title} #{arrowfinal}".html_safe, {column: column, direction: direction}
  end

  def arrow(column)
    if params[:column] != column
      " ".html_safe
    elsif params[:direction] == 'asc'
      "<span class='fa fa-caret-up'></span>".html_safe
    else params[:direction] == 'desc'
      "<span class='fa fa-caret-down'></span>".html_safe
    end
  end

  def modified_notice
    if notice == nil
      "".html_safe
    else
      add_edit_action_notice
    end
  end

  def add_edit_action_notice
  "<div class='alert alert-success alert-dismissable'>
    <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>x</button>
    <strong> #{notice} </strong>
  </div>".html_safe
  end

end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= form.label :name, :class => "control-label col-md-1" %></td>
      <td><%= form.text_field :name %></td>
    </tr>
    <tr>
      <td><%= form.label :surname, :class => "control-label col-md-1" %></td>
      <td><%= form.text_field :surname %></td>
    </tr>
    <tr>
      <td><%= form.label :nickname, :class => "control-label col-md-1" %></td>
      <td><%= form.text_field :nickname %></td>
    </tr>
    <tr>
      <td><%= form.label :salary, :class => "control-label col-md-1" %></td>
      <td><%= form.text_field :salary %></td>
    </tr>
    <tr>
      <td><%= form.label "Birthday", :class => "control-label col-md-1" %></td>
      <td><%= form.date_select :date_of_birth, :start_year=>1900, :order=>[:day, :month, :year] %></td>
    </tr>
    <tr>
      <td><%= form.label "Team", :class => "control-label col-md-1" %></td>
      <td><%= form.collection_select :team_id, @teams, :id, :name, include_blank: true%></td>
    </tr>
  </table>
  <div class="field" style="margin-top: 10px;">
    <%= form.submit 'Save', :class => "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/players/_navbarindex.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mynavbar">
  <div class="container">
    <div class="navbar-header">
       <a class="navbar-brand" href="/"><span class='fa fa-gamepad'></span> CS:GO</a>
    </div>
    <div class="navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "Players", players_path, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to "Teams", teams_path, :class => "nav-link" %></li>
        <li class="nav-item"><%= link_to "Match History", matches_path, :class => "nav-link" %></li>
      </ul>
    </div>

    <div class="divrightoriented">
        <%= form_tag(players_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search for players" %>
          <div class="btn-group minebtn btn-sm" role="group">
            <%= button_tag(type: 'submit', class: "btn btn-search btn-sm") do %>
              <span class='fa fa-search'></span>
            <% end %>
            <%= link_to(raw('<span class="fa fa-times"></span>'), players_path, class: 'btn btn-custom minebtn btn-sm') %>
          </div>
        <% end %>

        <% if @players.blank? && Player.count != 0 %>
          <h6>There are no teams which name contains '<%= params[:search] %>' &emsp;</h6>
        <% end %>
        <% if Player.count == 0 %>
          There are no games &emsp;
        <% end %>
    </div>
  </div>
</nav>

app/views/players/_old_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= form.label :name, :class => "control-label col-md-1" %>
  <%= form.text_field :name, :class => "col-md-3" %>
</div>

<div class="field">
  <%= form.label :surname, :class => "control-label col-md-1" %>
  <%= form.text_field :surname, :class => "col-md-3" %>
</div>

<div class="field">
  <%= form.label :nickname, :class => "control-label col-md-1" %>
  <%= form.text_field :nickname, :class => "col-md-3" %>
</div>

<div class="field">
  <%= form.label :salary, :class => "control-label col-md-1" %>
  <%= form.text_field :salary, :class => "col-md-3" %>
</div>

<div class="field">
  <%= form.label "Birthday", :class => "control-label col-md-1" %>
  <%= form.date_select :date_of_birth, :start_year=>1900, :order=>[:day, :month, :year] %>
</div>
<div class="field" style="margin-top: 10px;">
  <%= form.submit 'Save', :class => "btn btn-success btn-sm" %>
</div>
<% end %>

app/views/players/edit.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Edit Player:  <%= @player.name %> "<%= @player.nickname %>" <%= @player.surname %></h2>
    </div>

    <hr />

    <%= render 'form', player: @player %>

    <hr />

    <%= link_to 'Show', @player , :class => "btn btn-warning btn-sm" %>
    <%= link_to 'Back', players_path, :class => "btn btn-primary btn-sm" %>

</div>

app/views/players/index.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<% content_for :navbar do %>
     <%= render 'navbarindex' %>
<% end %>

<div class="container">
    <div class="d-inline-block">
        <h1>Players</h1>
    </div>
    <br/>

    <div class="d-inline-block float-left" style="margin-top: 10px;">
        <%= link_to 'Add Player', new_player_path, :class => "btn btn-primary btn-sm" %>
    </div>

    <table class="table table-stripped table-hover index indexborders">
      <thead>
        <tr>
          <th class="indexborders"><%= sort_link "name" %></th>
          <th class="indexborders"><%= sort_link "surname" %></th>
          <th class="indexborders"><%= sort_link "nickname" %></th>
          <th class="indexborders"><%= sort_link "date_of_birth" %></th>
          <th class="indexborders">Team</th>
          <th  class="indexborders" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= player.id %>"><%= player.name %></td>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= player.id %>"><%= player.surname %></td>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= player.id %>"><%= player.nickname %></td>
            <td class="nontextfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= player.id %>"><%= player.date_of_birth.strftime("%d.%m.%Y") %></td>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= player.id %>">
                <% if player.team.present? %>
                  <%= link_to player.team.name, player.team%>
                <% end %>
            </td>

            <!-- modalShowRow -->
            <div class="modal fade" id="modalShowRow<%= player.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">'<b><%= player.nickname %></b>' player details</h4>
                  </div>
                  <div class="modal-body">
                    <b> Name:  </b> <%= player.name %> <br/>
                    <b> Surame:  </b> <%= player.surname %> <br/>
                    <b> Nickname:  </b> <%= player.nickname %> <br/>
                    <b> Date of birth:  </b> <%= player.date_of_birth.strftime("%d.%m.%Y") %> <br/>
                    <% if player.team.present? %>
                      <b> Team:  </b> <%= link_to player.team.name, player.team%> <br/>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <!-- end of modalShowRow -->

            <td align=center class="indexborders">
              <button type="button" class="btn btn-warning minebtn btn-sm" data-toggle="modal" data-target="#modalShowRow<%= player.id %>">Show</button>
                <%= link_to 'Edit', edit_player_path(player), :class => "btn btn-success btn-sm" %>
                <button type="button" class="btn btn-danger minebtn btn-sm" data-toggle="modal" data-target="#modalDelete<%= player.id %>">Delete</span></button>

                <!-- modalDelete -->
                <div class="modal fade" id="modalDelete<%= player.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Delete confirmation</h4>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to delete this player: <br/>
                        <%= player.name %> '<%= player.nickname %>' <%= player.surname %>?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default minebtn btn-sm" data-dismiss="modal">No</button>
                        <%= link_to 'Delete', player, method: :delete, :class => "btn btn-danger minebtn btn-sm" %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end of modalDelete -->
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>

</div>

app/views/players/new.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Create New Player</h2>
    </div>

    <hr />

    <%= render 'form', player: @player %>

    <hr />

    <%= link_to 'Back', players_path, :class => "btn btn-primary btn-sm" %>

</div>

app/views/players/show.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Player: <%= @player.name %> "<%= @player.nickname %>" <%= @player.surname %></h2>
    </div>

    <hr />
    <p>
      <strong>Name:</strong>
      <%= @player.name %>
    </p>

    <p>
      <strong>Surname:</strong>
      <%= @player.surname %>
    </p>

    <p>
      <strong>Nickname:</strong>
      <%= @player.nickname %>
    </p>

    <p>
      <strong>Salary:</strong>
      <%= @player.salary %>
    </p>

    <p>
      <strong>Date of birth:</strong>
      <%= @player.date_of_birth.strftime("%d.%m.%Y") %>
    </p>

    <p>
      <strong>Team:</strong>
      <% if @player.team.present? %>
        <%= link_to @player.team.name, @player.team %>
      <% end %>
    </p>

    <hr />

    <%= link_to 'Edit', edit_player_path(@player), :class => "btn btn-success btn-sm" %>
    <%= link_to 'Delete', @player, method: :delete, data: { confirm: 'Are you sure you want to delete this player?' }, :class => "btn btn-danger btn-sm" %>
    <%= link_to 'Back', players_path, :class => "btn btn-primary btn-sm" %>

</div>