config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :teams
  resources :matches
  resources :pages
  root 'pages#index'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team_one, class_name: "Team", foreign_key: "team_one_id"
  belongs_to :team_two, class_name: "Team", foreign_key: "team_two_id"
  validate :date_of_match_in_future?
  validate :different_teams?
  validates :result, :format => {
    :with => /\A([0-9]:[0-9])|([1-9][0-9]*:[1-9][0-9]*)|([0-9]:[1-9][0-9]*)|([1-9][0-9]*:[0-9])\z/,
    :message => " accepts format of 'number:number'"
  }

  private

  def different_teams?
    if(self.team_one != nil && self.team_two != nil)
      if self.team_one.id == self.team_two.id
        errors.add("Team cannot play", "against itself")
      end
    end
  end

  def date_of_match_in_future?
   if self.date > Date.today
     errors.add("Date of match", "cannot be in the future")
   end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  def index
    @matches = Match.all
  end

  def show
  end

  def new
    @match = Match.new
    @teams = Team.all.order(:name)
  end

  def edit
    @teams = Team.all.order(:name)
  end

  def create
    @match = Match.new(match_params)
    @teams = Team.all.order(:name)

    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @teams = Team.all.order(:name)
    if @match.update(match_params)
      redirect_to @match, notice: 'Match was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_path, notice: 'Match was successfully deleted.'
  end

  private

    def set_match
      @match = Match.find(params[:id])
    end

    def match_params
      params.require(:match).permit(:team_one_id, :team_two_id, :result, :date)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper

  def modified_notice
    if notice == nil
      "".html_safe
    else
      add_edit_action_notice
    end
  end

  def add_edit_action_notice
  "<div class='alert alert-success alert-dismissable'>
    <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>x</button>
    <strong> #{notice} </strong>
  </div>".html_safe
  end

end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>
      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= form.label "Team one" %></td>
      <td><%= form.collection_select :team_one_id, @teams, :id, :name, include_blank: true%></td>
    </tr>
    <tr>
      <td><%= form.label "Team two" %></td>
      <td><%= form.collection_select :team_two_id, @teams, :id, :name, include_blank: true%></td>
    </tr>
    <tr>
      <td><%= form.label :result, :class => "control-label col-md-1" %></td>
      <td><%= form.text_field :result %></td>
    </tr>
    <tr>
      <td><%= form.label :date, :class => "control-label col-md-1" %></td>
      <td><%= form.date_select :date, :start_year=>1900, :order=>[:day, :month, :year] %></td>
    </tr>
  </table>
  <div class="field" style="margin-top: 10px;">
    <%= form.submit 'Save', :class => "btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Edit Match (<%= @match.id %>)</h2>
    </div>

    <hr />

    <%= render 'form', match: @match %>

    <hr />

    <%= link_to 'Show', @match , :class => "btn btn-warning btn-sm" %>
    <%= link_to 'Back', matches_path, :class => "btn btn-primary btn-sm" %>

</div>

app/views/matches/index.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h1>Match History</h1>
    </div>
    <br/>
    <div class="d-inline-block float-left" style="margin-top: 10px;">
        <%= link_to 'Add Match', new_match_path, :class => "btn btn-primary btn-sm" %>
    </div>

    <table class="table table-stripped table-hover  index indexborders">
      <thead>
        <tr>
          <th class="indexborders">First team</th>
          <th class="indexborders">Second team</th>
          <th class="indexborders">Result</th>
          <th class="indexborders">Date</th>
          <th class="indexborders" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= match.id %>">
              <% if match.team_one != nil %>
                <%= link_to match.team_one.name, match.team_one%>
              <% else %>
                <i>Team does not exist</i>
              <% end %>
            </td>
            <td class="textfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= match.id %>">
              <% if match.team_two != nil %>
                <%= link_to match.team_one.name, match.team_one%>
              <% else %>
                <i>Team does not exist</i>
              <% end %>
            </td>
            <td class="nontextfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= match.id %>"><%= match.result %></td>
            <td class="nontextfield indexborders" data-toggle="modal" data-target="#modalShowRow<%= match.id %>"><%= match.date %></td>

            <!-- modalShowRow -->
            <div class="modal fade" id="modalShowRow<%= match.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Match details</h4>
                  </div>
                  <div class="modal-body">
                    <b> Team one name: </b>
                      <% if match.team_one != nil %>
                        <%= match.team_one.name %>
                      <% else %>
                        <i>Team does not exist</i>
                      <% end %><br/>
                    <b> Team two name: </b>
                      <% if match.team_two != nil %>
                        <%= match.team_two.name %>
                      <% else %>
                        <i>Team does not exist</i>
                      <% end %><br/>
                    <b> Result:  </b> <%= match.result %> <br/>
                    <b> Date:  </b> <%= match.date %> <br/>
                  </div>
                </div>
              </div>
            </div>
            <!-- end of modalShowRow -->

            <td align=center class="indexborders">
                <button type="button" class="btn btn-warning minebtn btn-sm" data-toggle="modal" data-target="#modalShowRow<%= match.id %>">Show</button>
                <%= link_to 'Edit', edit_match_path(match), :class => "btn btn-success btn-sm" %>
                <button type="button" class="btn btn-danger minebtn btn-sm" data-toggle="modal" data-target="#modalDelete<%= match.id %>">Delete</span></button>

                <!-- modalDelete -->
                <div class="modal fade" id="modalDelete<%= match.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">Delete confirmation</h4>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to delete this match: <br/>
                        <b><% if match.team_one != nil %>
                          <%= match.team_one.name %>
                        <% else %>
                          <i>Team does not exist</i>
                        <% end %></b> vs
                        <b><% if match.team_two != nil %>
                          <%= match.team_two.name %>
                        <% else %>
                          <i>Team does not exist</i>
                        <% end %></b>?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default minebtn btn-sm" data-dismiss="modal">No</button>
                        <%= link_to 'Delete', match, method: :delete, :class => "btn btn-danger minebtn btn-sm" %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end of modalDelete -->
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

</div>

app/views/matches/new.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Create New Match</h2>
    </div>

    <hr />

    <%= render 'form', match: @match %>

    <hr />

    <%= link_to 'Back', matches_path, :class => "btn btn-primary btn-sm" %>

</div>

app/views/matches/show.html.erb
<p id="notice" class="text-center"><%= modified_notice %></p>

<div class="container">
    <div class="d-inline-block">
        <h2>Match (<%= @match.id %>)</h2>
    </div>

    <hr />

    <p>
      <strong>Team one:</strong>
      <% if @match.team_one != nil %>
        <%= link_to @match.team_one.name, @match.team_one %>
      <% else %>
        <i>Team does not exist</i>
      <% end %>
    </p>

    <p>
      <strong>Team two:</strong>
      <% if @match.team_two != nil %>
        <%= link_to @match.team_two.name, @match.team_two %>
      <% else %>
        <i>Team does not exist</i>
      <% end %>
    </p>

    <p>
      <strong>Result:</strong>
      <%= @match.result %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @match.date.strftime("%d.%m.%Y") %>
    </p>

    <hr />

    <%= link_to 'Edit', edit_match_path(@match), :class => "btn btn-success btn-sm" %>
    <%= link_to 'Delete', @match, method: :delete, data: { confirm: 'Are you sure you want to delete this match?' }, :class => "btn btn-danger btn-sm" %>
    <%= link_to 'Back', matches_path, :class => "btn btn-primary btn-sm" %>

</div>